- name: Deploy to EC2 via SSH
            uses: appleboy/ssh-action@v1.0.3
            with:
              host: ${{ secrets.EC2_HOST }}
              username: ${{ secrets.EC2_USER }}
              key: ${{ secrets.SSH_PRIVATE_KEY }}
              script: |
                # 1. Navigate to your application's directory on EC2
                # IMPORTANT: Adjusted path based on your input
                cd /home/ec2-user/studio/server

                # 2. Pull the latest code from GitHub
                git pull origin main # Adjust branch name if different

                # 3. Install Node.js dependencies on EC2
                npm install

                # 4. Rebuild the TypeScript project on EC2
                npm run build

                # 5. Stop the existing PM2 process gracefully (if running)
                # IMPORTANT: Use the PM2 app name you prefer, e.g., 'studio-server'
                pm2 stop studio-server || true

                # 6. Start/Restart the application with PM2
                # IMPORTANT: Entry point now points to 'dist/index.js' within your server directory
                pm2 start dist/index.js --name studio-server --watch --ignore-watch="node_modules" --no-daemon

                # 7. Save PM2 process list
                pm2 save