name: Deploy Server to EC2

on:
  push:
    branches: [ main ]
    paths: [ 'server/index.ts' ]  # Only deploy when server file changes

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ec2-user
        key: ${{ secrets.EC2_KEY }}
        script: |
          cd ~/chat/server
          git pull origin main
          npm install
          npm run build
          pm2 restart socket-server
